# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1281, 681)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1493, 681))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(899, 200))
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 640))
        self.centralwidget.setMaximumSize(QtCore.QSize(9900, 640))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBoxSpeed = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxSpeed.setEnabled(True)
        self.groupBoxSpeed.setObjectName("groupBoxSpeed")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBoxSpeed)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.speedspinBox = QtWidgets.QSpinBox(self.groupBoxSpeed)
        self.speedspinBox.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.speedspinBox.setFont(font)
        self.speedspinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speedspinBox.setMaximum(250)
        self.speedspinBox.setSingleStep(8)
        self.speedspinBox.setObjectName("speedspinBox")
        self.horizontalLayout_2.addWidget(self.speedspinBox)
        self.speedSlider = QtWidgets.QSlider(self.groupBoxSpeed)
        self.speedSlider.setEnabled(True)
        self.speedSlider.setMinimum(0)
        self.speedSlider.setMaximum(250)
        self.speedSlider.setSingleStep(8)
        self.speedSlider.setPageStep(8)
        self.speedSlider.setSliderPosition(0)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.speedSlider.setTickInterval(384)
        self.speedSlider.setObjectName("speedSlider")
        self.horizontalLayout_2.addWidget(self.speedSlider)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.speedChangeButton = QtWidgets.QPushButton(self.groupBoxSpeed)
        self.speedChangeButton.setMinimumSize(QtCore.QSize(30, 50))
        self.speedChangeButton.setObjectName("speedChangeButton")
        self.horizontalLayout_4.addWidget(self.speedChangeButton)
        self.horizontalLayout_5.addWidget(self.groupBoxSpeed)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBoxPosition = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPosition.setEnabled(True)
        self.groupBoxPosition.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxPosition.setObjectName("groupBoxPosition")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxPosition)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.positionspinBox = QtWidgets.QSpinBox(self.groupBoxPosition)
        self.positionspinBox.setMinimumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.positionspinBox.setFont(font)
        self.positionspinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.positionspinBox.setMinimum(-16000)
        self.positionspinBox.setMaximum(16000)
        self.positionspinBox.setSingleStep(10)
        self.positionspinBox.setObjectName("positionspinBox")
        self.gridLayout_5.addWidget(self.positionspinBox, 1, 0, 1, 1)
        self.positionSlider = QtWidgets.QSlider(self.groupBoxPosition)
        self.positionSlider.setEnabled(True)
        self.positionSlider.setMinimum(-16000)
        self.positionSlider.setMaximum(16000)
        self.positionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.positionSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.positionSlider.setTickInterval(2000)
        self.positionSlider.setObjectName("positionSlider")
        self.gridLayout_5.addWidget(self.positionSlider, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.posChangeButton = QtWidgets.QPushButton(self.groupBoxPosition)
        self.posChangeButton.setMinimumSize(QtCore.QSize(0, 50))
        self.posChangeButton.setObjectName("posChangeButton")
        self.horizontalLayout.addWidget(self.posChangeButton)
        self.horizontalLayout_6.addWidget(self.groupBoxPosition)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 4, 1, 1)
        self.groupBoxDirection = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDirection.setObjectName("groupBoxDirection")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBoxDirection)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButtonDirectionAntiClockwise = QtWidgets.QRadioButton(self.groupBoxDirection)
        self.radioButtonDirectionAntiClockwise.setObjectName("radioButtonDirectionAntiClockwise")
        self.gridLayout_8.addWidget(self.radioButtonDirectionAntiClockwise, 2, 0, 1, 1)
        self.radioButtonDirectionClockWise = QtWidgets.QRadioButton(self.groupBoxDirection)
        self.radioButtonDirectionClockWise.setObjectName("radioButtonDirectionClockWise")
        self.gridLayout_8.addWidget(self.radioButtonDirectionClockWise, 1, 0, 1, 1)
        self.radioButtonDirectionStop = QtWidgets.QRadioButton(self.groupBoxDirection)
        self.radioButtonDirectionStop.setChecked(True)
        self.radioButtonDirectionStop.setObjectName("radioButtonDirectionStop")
        self.gridLayout_8.addWidget(self.radioButtonDirectionStop, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxDirection, 0, 3, 1, 1)
        self.groupBoxAcceleration = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxAcceleration.setEnabled(False)
        self.groupBoxAcceleration.setObjectName("groupBoxAcceleration")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBoxAcceleration)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.radioButtonPositionCtrl = QtWidgets.QRadioButton(self.groupBoxAcceleration)
        self.radioButtonPositionCtrl.setChecked(True)
        self.radioButtonPositionCtrl.setObjectName("radioButtonPositionCtrl")
        self.gridLayout_10.addWidget(self.radioButtonPositionCtrl, 0, 0, 1, 1)
        self.radioButtonSpeedCtrl = QtWidgets.QRadioButton(self.groupBoxAcceleration)
        self.radioButtonSpeedCtrl.setObjectName("radioButtonSpeedCtrl")
        self.gridLayout_10.addWidget(self.radioButtonSpeedCtrl, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxAcceleration, 0, 1, 1, 1)
        self.groupBoxControlSelection = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxControlSelection.setEnabled(True)
        self.groupBoxControlSelection.setObjectName("groupBoxControlSelection")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBoxControlSelection)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButtonResetInputs = QtWidgets.QPushButton(self.groupBoxControlSelection)
        self.pushButtonResetInputs.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButtonResetInputs.setCheckable(False)
        self.pushButtonResetInputs.setObjectName("pushButtonResetInputs")
        self.gridLayout_9.addWidget(self.pushButtonResetInputs, 2, 0, 1, 1)
        self.pushButtonEnableMotorCtrl = QtWidgets.QPushButton(self.groupBoxControlSelection)
        self.pushButtonEnableMotorCtrl.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButtonEnableMotorCtrl.setCheckable(True)
        self.pushButtonEnableMotorCtrl.setObjectName("pushButtonEnableMotorCtrl")
        self.gridLayout_9.addWidget(self.pushButtonEnableMotorCtrl, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxControlSelection, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.graphicsViewBVDD = PlotWidget(self.groupBox)
        self.graphicsViewBVDD.setObjectName("graphicsViewBVDD")
        self.gridLayout_7.addWidget(self.graphicsViewBVDD, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsViewTemperature = PlotWidget(self.groupBox_2)
        self.graphicsViewTemperature.setObjectName("graphicsViewTemperature")
        self.gridLayout_3.addWidget(self.graphicsViewTemperature, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 3, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graphicsViewRotorSpeed = PlotWidget(self.groupBox_3)
        self.graphicsViewRotorSpeed.setObjectName("graphicsViewRotorSpeed")
        self.gridLayout_6.addWidget(self.graphicsViewRotorSpeed, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelErrorLED = QtWidgets.QLabel(self.centralwidget)
        self.labelErrorLED.setMinimumSize(QtCore.QSize(25, 25))
        self.labelErrorLED.setMaximumSize(QtCore.QSize(25, 25))
        self.labelErrorLED.setText("")
        self.labelErrorLED.setPixmap(QtGui.QPixmap(":/led/resources/red-led-off.png"))
        self.labelErrorLED.setScaledContents(True)
        self.labelErrorLED.setAlignment(QtCore.Qt.AlignCenter)
        self.labelErrorLED.setObjectName("labelErrorLED")
        self.verticalLayout_8.addWidget(self.labelErrorLED, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 4, 3, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelOverCurrentLED = QtWidgets.QLabel(self.centralwidget)
        self.labelOverCurrentLED.setMinimumSize(QtCore.QSize(25, 25))
        self.labelOverCurrentLED.setMaximumSize(QtCore.QSize(25, 25))
        self.labelOverCurrentLED.setText("")
        self.labelOverCurrentLED.setPixmap(QtGui.QPixmap(":/led/resources/red-led-off.png"))
        self.labelOverCurrentLED.setScaledContents(True)
        self.labelOverCurrentLED.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOverCurrentLED.setObjectName("labelOverCurrentLED")
        self.verticalLayout_6.addWidget(self.labelOverCurrentLED, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 4, 4, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelOverTemperatureLED = QtWidgets.QLabel(self.centralwidget)
        self.labelOverTemperatureLED.setMinimumSize(QtCore.QSize(25, 25))
        self.labelOverTemperatureLED.setMaximumSize(QtCore.QSize(25, 25))
        self.labelOverTemperatureLED.setText("")
        self.labelOverTemperatureLED.setPixmap(QtGui.QPixmap(":/led/resources/red-led-off.png"))
        self.labelOverTemperatureLED.setScaledContents(True)
        self.labelOverTemperatureLED.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOverTemperatureLED.setObjectName("labelOverTemperatureLED")
        self.verticalLayout_7.addWidget(self.labelOverTemperatureLED, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 4, 5, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.currentPositionLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.currentPositionLCD.setMinimumSize(QtCore.QSize(100, 0))
        self.currentPositionLCD.setDigitCount(6)
        self.currentPositionLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.currentPositionLCD.setObjectName("currentPositionLCD")
        self.verticalLayout_9.addWidget(self.currentPositionLCD)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelTargetOnlineLED = QtWidgets.QLabel(self.centralwidget)
        self.labelTargetOnlineLED.setMinimumSize(QtCore.QSize(25, 25))
        self.labelTargetOnlineLED.setMaximumSize(QtCore.QSize(25, 25))
        self.labelTargetOnlineLED.setText("")
        self.labelTargetOnlineLED.setPixmap(QtGui.QPixmap(":/led/resources/green-led-off.png"))
        self.labelTargetOnlineLED.setScaledContents(True)
        self.labelTargetOnlineLED.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTargetOnlineLED.setObjectName("labelTargetOnlineLED")
        self.verticalLayout_4.addWidget(self.labelTargetOnlineLED, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 4, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_11.addLayout(self.verticalLayout, 0, 3, 1, 1)
        self.ImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.ImageButton.setMinimumSize(QtCore.QSize(400, 622))
        self.ImageButton.setMaximumSize(QtCore.QSize(400, 622))
        self.ImageButton.setAutoFillBackground(False)
        self.ImageButton.setStyleSheet("border-image: url(:/Image/resources/NT_BannerSW31.png);")
        self.ImageButton.setText("")
        self.ImageButton.setFlat(False)
        self.ImageButton.setObjectName("ImageButton")
        self.gridLayout_11.addWidget(self.ImageButton, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1281, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuClose = QtWidgets.QMenu(self.menubar)
        self.menuClose.setObjectName("menuClose")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuClose.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NTMicroDrive"))
        self.groupBoxSpeed.setTitle(_translate("MainWindow", "Speed [PPS]"))
        self.speedChangeButton.setText(_translate("MainWindow", "Change"))
        self.groupBoxPosition.setTitle(_translate("MainWindow", "Position [microsteps]"))
        self.posChangeButton.setText(_translate("MainWindow", "Change"))
        self.groupBoxDirection.setTitle(_translate("MainWindow", "Direction"))
        self.radioButtonDirectionAntiClockwise.setText(_translate("MainWindow", "anti-clockwise"))
        self.radioButtonDirectionClockWise.setText(_translate("MainWindow", "clockwise"))
        self.radioButtonDirectionStop.setText(_translate("MainWindow", "stop"))
        self.groupBoxAcceleration.setTitle(_translate("MainWindow", "Control Options"))
        self.radioButtonPositionCtrl.setText(_translate("MainWindow", "Position Control"))
        self.radioButtonSpeedCtrl.setText(_translate("MainWindow", "Speed Control"))
        self.groupBoxControlSelection.setTitle(_translate("MainWindow", "Motor Control"))
        self.pushButtonResetInputs.setText(_translate("MainWindow", "Reset Inputs"))
        self.pushButtonEnableMotorCtrl.setText(_translate("MainWindow", "Enable Motor Control"))
        self.groupBox.setTitle(_translate("MainWindow", "BVDD"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Temperature"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Rotor Speed"))
        self.label_10.setText(_translate("MainWindow", "  Error  "))
        self.label_6.setText(_translate("MainWindow", "  Over Current  "))
        self.label_8.setText(_translate("MainWindow", "  Over Temperature  "))
        self.label_11.setText(_translate("MainWindow", "Current Position"))
        self.label_2.setText(_translate("MainWindow", "  Target Online  "))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuClose.setTitle(_translate("MainWindow", "App"))

from pyqtgraph import PlotWidget
from . import resources_rc
